version: '3'
services:
  mysql:
    build:
      context: docker/
    volumes:
      - ./docker/db-data:/var/lib/mysql
      - type: bind
        source: 'docker/my.cnf'
        target: '/etc/mysql/conf.d/my.cnf'
    container_name: e-plus-plus-db
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-e-ten}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      TZ: 'Asia/Tokyo'

volumes:
  db-data:
    driver: local
